### ISSUE TITLE
Diseño de home page

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#15]
1.- Cambiar color negro de hasta arriba por rosa con el RGB.
2.- Poner el logo en el centro en lo blanco.
3.- Cambiar la foto de homepage principal por la foto de la chava agarrando su cabello con anillos.
4.- Cambiar las tres fotos (las que estan dificiles de cambiar) a fotos de tres productos y que tengan el precio abajo

**Comment by Ganacontrol** [comment]
1.- Done
2.- Done
3.- Done
4.- Abajo de esas 3, puse una seccion de "Featured products" y le puse 4 columnas, ahora nadamas se ven dos porque solo hay dos productos agregados. Le puedo poner 3 si quieres tres, yo pienso que caben mejor 4.

La seccion donde hay 3 fotos que pusimos random arriba de featured products la puedo quitar si quieres pero yo pienso que deberiamos aprovecharla para poner links a Discover yourself, About y otra cosa mas o solo esas dos como ves?

On another note, has pensado en ofrecer free shipping?  Muchas tiendas dicen free shipping y le suben un poco el precio a los productos para cubrir ese costo. Pero la gente le encanta escuchar "Free shipping"

Otra cosa que podria hacer por ti en cuanto a shipping es poner alguna regla por precio. "Si el carrito es mayor a 'x' entonces el shipping es gratis"

Think about it.

**Comment by myfreckle** [comment]
1- cool
2- super cool
3- creo que sale la misma foto de la chava del demo jajjaja esa la neta no se como cambiarla (la de slide) y que salen dos fotos.
4- super bien! si creo que caben 4 y esta chido! ahorita que suba mas productos a ver si se pueden poner ahi. 
Lo de 3 fotos random arriba de featured products se ve cool, voy a pensar que fotos quedan mejor ahi. pero si esta cool dejarla. podrian ser fotos de instagram (hay forma de poner las fotos de instagram y que se vean automatico ahi? no todas pero tipo las ultimas tres o algo asi?)
Buen punto lo de free shipping. la neta son $90 en todo mexico entonces si podria ver como hacerle para cambiar el precio y que se vea el free shipping. esta cool la idea! Thx!

**Comment by myfreckle** [comment]
Otra cosa, veo que cuando seleccionas en home el menu, sale de color como cafesoso. que se cambie a rosa. y checar la type con la de Lora que tenia en mi pdf. te lo puedo mandar por mail si quieres

**Comment by Ganacontrol** [comment]
Ya cambie los colores del menu cuando pasas el mouse y tambien cuando te encuentras en esa seccion al rosa

**Comment by Ganacontrol** [comment]
3.- Done
4.- Done, se podran en automatico cuando los arregles.

Sobre el color cafesoso ya esta arreglado, y la font tiene su propio issue.
Cuando sepas que hacer con lo demas de la home y el shipping abrimos otro issue. 
Este debe morir.

**Comment by myfreckle** [comment]
La foto de Home, de la chava agarrandose el pelo. siento que abres la pagina y ves pelo... hay forma de mandartela cortada y sea mas chico (de largo) para que se enfoquen los anillos?

**Comment by Ganacontrol** [comment]
Si... la puedes recortar el problema es la resolucion, lo intente yo y se veia pixeleada recortada y luego agrandada. Hice algunos cambios aqui , velos. 

Si quieres cambiar la imagen por otra esta bien, solo toma en cuenta el (full screen de 1048px para la gente normal, y 3960px para pantallas 4K) , del width osea lo largo arriba abajo damelo del tama;o que lo quieras.

**Comment by Ganacontrol** [comment]
2212x600 px es el tama;o actual de lado a lado y arriba abajo del slider.

**Comment by myfreckle** [comment]
type: manus trial

**Comment by Ganacontrol** [comment]
Hover mouse fondo rosa en los shop filters

Dejar las fotos y quitar bonotes/links en homepage de las 3 imagenes.	

cambiar link del boton de discove ryourself en la homepage al correcto
