### ISSUE TITLE
Discover Yourself Page

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#16]
Poner el test en esta pagina, que dandole click salga el test directo.

**Comment by Ganacontrol** [comment]
Me asignare este issue a mi.

**Comment by Ganacontrol** [comment]
Disover Yourself y test centrado.
Blanco fondo letras negrs
pasas el mouse  letras negras con fondo rosa
y cuando das click fondo negro con letras blancas
