### ISSUE TITLE
Diseño de My Freckle

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#18]
Tengo dudas de como se va a ver o como se puede ver cuando le des click en finalizar tu compra o en (my freckle) que puedo manipular y que no, porque por Paypal y las otras formas de pago tengo entendido que no todo se puede manipular.

**Comment by Ganacontrol** [comment]
Justo eso lo estoy trabajando en el #22, Paypal no hay nada que puedas hacer mas que poner tu nombre y logo. En cuanto a pagar por tarjeta /oxxo aun estoy en eso, cuando acabe te lo ense;o.

**Comment by myfreckle** [comment]
va!
