### ISSUE TITLE
Agregar coming soon con logo/animacion

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#2]
Configurar una coming soon page mientras esta lista la pagina.

@myfreckle  Necesito el archivo del logo en .PNG y el archivo de lo demas que queramos poner en la coming soon page.

**Comment by Ganacontrol** [comment]
Ya funciona la coming soon page. Puse el logo falta la animacion

**Comment by myfreckle** [comment]
y se ve cool! (y)
