### ISSUE TITLE
Filtros para la shop page

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#21]
Instalar un sidebar con categorias y filtros de precio.

**Comment by Ganacontrol** [comment]
Done y Filtrar por precio esta del lado derecho.

**Comment by myfreckle** [comment]
cool! ya vi que salen alado y se ve bien!
crees que puedas cambiar type y poner un cuadro rosa abajo de las palabras que se seleccionen? te paso screen en slack ahorita para que veas a lo que me refiero con esto

**Comment by Ganacontrol** [comment]
Done.
