### ISSUE TITLE
Set up the shopping cart y pagos

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#22]
Configurar modo de prueba para pagos con tarjeta/oxxo

**Comment by Ganacontrol** [comment]
Para hacer este issue necesito que hagas el #23

**Comment by Ganacontrol** [comment]
Ya quedo conekta, asumiendo que te acepten.
Aun me falta Stripe y Paypal.

**Comment by myfreckle** [comment]
conekta wuwu

**Comment by myfreckle** [comment]
mail a stripe check
