### ISSUE TITLE
The Freckle Cart!

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#24]
Cambiar el grafico del carrito por un freckle, surgen dudas como... actualmente el carrito tiene el numero de items agregados - dentro del grafico... entonces,
Queremos mantener eso? En caso de que si, Necesitaría el freckle de 43px x 38px con el hueco en medio y obvio fondo transparente y también el hueco debe ser transparente!

En caso de que no, como quiera necesito el freckle de ese tamaño y transparente pero sin el hueco enmedio.

**Comment by myfreckle** [comment]
deja te la mando!
me gusta la idea de solo la esfera negra. te la paso sin hueco por slack!

**Comment by myfreckle** [comment]
listo! te la mande con el nombre: esfera3

**Comment by Ganacontrol** [comment]
Done
