### ISSUE TITLE
TEST para el fin de semana!

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#25]
Te tengo una super super duda. Este fin de semana tengo una expo, y para unas piezas se necesita el Test! 
Desde Febrero que saque estas piezas lo que hacia era usar el test desde la pagina de jorgemendieta.xyz .... para este fin que me recomiendas que haga? 
Lo que necesito es que la gente use el test lo conteste y al final le salga la respuesta.

**Comment by Ganacontrol** [comment]
Hay otro issue para este, y se cancelo lo de para el fin de semana.
