### ISSUE TITLE
Footer set up

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#30]
Que queremos poner en el footer? Hay cuatro columnas. Any ideas?

**Comment by myfreckle** [comment]
te mando un screen de como lo veía antes en slack

**Comment by myfreckle** [comment]
con esto, nace otro issue para mucho despues.. .cambio de mi mail. actualmente uso: my_freckle@hotmail.com... me gustaría uno nuevo.. te hago otro issue

**Comment by Ganacontrol** [comment]
Done como en el screenshot pero obvio faltan poner mas cosas no? Se ve vacio enmedio no esta balanceado.
