### ISSUE TITLE
Backorder

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#37]
Aviso al cliente que si no hay en stock, que se tarda 2 semanas máximo en llegarle (sin contar el tiempo del shipping)

**Comment by Ganacontrol** [comment]
Notice upon adding to cart about stock availability.

**Comment by Ganacontrol** [comment]
Cambiar a rojo y que diga "It will ship after 2 weeks from ordering plus regular shipping time"
