### ISSUE TITLE
FACEBOOK!

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#38]
Ok se me ocurrió contarte de un problema que tengo de fb jaja a ver si sabes como hacerle! 
En mi FB puedes tener tipo tu user. www.facebook.com/yessica.ramirez ...
Con freckle me paso algo...
cuando empecé hice una pagina de prueba de otra marca y le puse de user "nievedeverano" fue una tonteria y nadamas fue para ver como funcionaba todo este show... y cuando ya empece mi marca empecé como "once upon a freckle" y con el tiempo decidi quedarme con Freckle, simple y al grano... pero ya habia puesto de user "nievedeverano" y luego lo cambie a "onceuponafreckle" y nunca pude cambiarlo a simplemten Freckle o My_Freckle o algo relacionado conmigo... entonces mi problema esque la gente que no tiene nada q ver con la gente que ya me sigue, no encuentra la pagina facil... ese es el problema. entonces e tratado de cambiarlo pero no puedo porque fb solo te deja cambiarlo dos veces. no se que hacer.. entonces hace unos meses abri otra pagina de fb con user www.facebook.com/my_freckle (porque todavia estaba disponible) y la tengo en Hide. (nadamas para que no me robaran ese user) ... total ese es un problemilla que nada q ver con la pagina pero queria saber si sabras como cambiarlo jaja

**Comment by Ganacontrol** [comment]
en resumen
quieres cambiar  el onceuponafreckle a my_freckle pero facebook no te deja cambiarlo mas de dos veces

**Comment by myfreckle** [comment]
o a freckle si es que se puede usar 
pero si, ese el problema
