### ISSUE TITLE
Shipping

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#44]
Duda sobre el shipping o cuando compran en linea. 
como es que no tengo la menor idea.. funciona asi?
Compran.. check out. ya van a pagar y
les preguntan si quieren recogerlo en la sucursal de monterrey / mandarlo por correo y que llegue en 2-3 dias habiles ?

**Comment by Ganacontrol** [comment]
Para deposito bancario, necesito que me des estos detalles:
Nombre de la cuenta	
Número de cuenta	
Nombre del banco	
CLABE Interbancaria

**Comment by Ganacontrol** [comment]
Agregar $50 USD de shipping para USA clients.

**Comment by Ganacontrol** [comment]
Tiempo de entrega en MX es de 3-4 dias habiles y out of stock es 2 semanas + 3-4 dias habiles

**Comment by Ganacontrol** [comment]
CAMBIO:  FREE SHIPPING PARA TODO MEXICO. $900.00 Free shipping.
