### ISSUE TITLE
Zoom fotos en store

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#53]
Al hacer zoom a las fotos en la pagina de la tienda cuando te metes a ver uno en específico sale un recuadro gris. Creo que se vería mas limpio sin el. :)

**Comment by Ganacontrol** [comment]
Lo siento, esto no es tan sencillo con la forma en la que lo hizo el autor, pero aumente el zoom %  cuando pasas el mouse si eso ayuda.  Checalo! Si no te molesta dejalo pasar yo creo qu se ve bien asi!

**Comment by Ganacontrol** [comment]
BOOM
