### ISSUE TITLE
Terms & Conditions page

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#56]
Anexo archivo

**Comment by Ganacontrol** [comment]
https://files.slack.com/files-pri/T0GRSUKAR-F1GGHJTK3/download/te__rminos-y-condiciones-de-freckle.docx

**Comment by Ganacontrol** [comment]
Tambien quitar el sidebar del about page por completo.

**Comment by myfreckle** [comment]
ya vi el linnk jij

**Comment by Ganacontrol** [comment]
done, done done
