### ISSUE TITLE
single product

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#61]
single product thumbnails de 2 - 4

**Comment by Ganacontrol** [comment]
Habia dos problemas aqui:
1) Que las fotos se veian raras, como alargadas hacia arriba
2) Querias subir de 2 a 4 productos.

La buena noticia es que el 1) Ya me parece resuelto, checalo.
La mala noticia es que el 1) hace el 2) imposible. Osea, si queremos que las imagenes se vean mas anchas o cuadradas, ocupa mas espacio  y no alcanza para meter 4 ahi. 

Checalo asi como esta haber que opinas o si los quieres mas anchos. pero meter 4 thumbnails ahi es demasiado si queremos que se vean "mas cuadradas" las thumbnails.

**Comment by Ganacontrol** [comment]
cambiar flechas a rosa en thumnails
