### ISSUE TITLE
Slidebar

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#66]
Footer slide bar no se que paso con ese issue no lo veo jaja, pero es poner todo el footer en un slidebar cuando le des click. a cualquiera de las opciones de abajo.

**Comment by myfreckle** [comment]
ya lo vi, pero creo que no en toas las opciones sale el slidebar. ahorita checo en cuales no

**Comment by myfreckle** [comment]
pag en español: preguntas freciuentes no sale nadamas

**Comment by Ganacontrol** [comment]
Checa esto de nuevo plz

**Comment by myfreckle** [comment]
ya sale 
CHECK
