### ISSUE TITLE
Descripciones de los resultados del test

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#69]
Tengo las descripciones de la personalidad en un PDF pero esas no vienen asi en los productos.. Que pondremos en el resultado del test como descripcion de la personalidad?

Usaremos texto o la foto?

Necesito una o la otra :)

**Comment by myfreckle** [comment]
el resultado del test no te puede llevar automaticamente a el producto seleccionado en la tienda?  .... osea si te sale "the idealist" que te salga literal ya como si te hubieras metido a ver los detalles?

**Comment by Ganacontrol** [comment]
Ya acordamos que esto no, pero dejoe ste issue abierto porque falta que me pases las descripciones de los productos como acordamos por telefono.

**Comment by Ganacontrol** [comment]
Notaras un ligero cambio cuando realizas el test, antes cuando respondias una respuesta era super super rapido que se cambiaba ala que sigue... ahora lo cambie a que se actualice la pagina con cada respuesta.... por dos razones.

1) De la manera pasada, cuando alguien hace el test solo cuenta como 1 visita a tu pagina, de esta manera, contara como 36 visitas. Porque quiero inflar el numero de visitas? Porque es un indicador para Google que tu pagina tiene  movimiento y la gente le gusta usarla. 

2) Creo que esa "animacion" que pasaba con el test, era lo que causaba que a veces el resultado se viera todo desformateado. Not sure la verdad, pero creo que si. De hecho ya no me ha pasado pero por si las moscas tambien es otro punto a favor.

En realidad tambien sigue siendo rapido, solo no TAN rapido.

**Comment by myfreckle** [comment]
ok sii me gustan los dos puntos entonces lo dejamos asi. sii vi que no es tan lenta entonces cool!!
