### ISSUE TITLE
size guide

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#70]
para este link 
https://freckle.com.mx/en/size-guide/
se puede que las fotos le des click y se hagan mas grandes? sin irse de la pagina pero chanse que se abra una ventanita o algo?

**Comment by Ganacontrol** [comment]
Ahora, puedes hacer click en la imagen y se abrira otra ventana con la foto en su tama;o original, en ambas versiones ingles y espa;ol lo cambie.

**Comment by myfreckle** [comment]
crees que se pueda hacer algo asi?
