### ISSUE TITLE
video sin lo negro

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#73]
yessi mandale a jorge el video bien para los productos.

**Comment by Ganacontrol** [comment]
Ahora si se ve el video sin lo negro. Mira!
https://freckle.com.mx/producto/love-me/

Hazlo entero y lo vuelvo a subir. Dejare esto en Review

**Comment by myfreckle** [comment]
cool!!! ok te lo mando ahorita!
