### ISSUE TITLE
mail de completado

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#78]
orden completada. tambien personalizarlo.

**Comment by myfreckle** [comment]
mail

**Comment by Ganacontrol** [comment]
Voy a grabar este codigo aqui, se lo tuve que quitar para que desaparezca el header de texto negro default de woocommerce


//////

                        	<tr>
                            	<td align="center" valign="top">
                                    
                                	<table border="0" cellpadding="0" cellspacing="0" width="600" id="template_header">
                                        <tr>
                                            <td id="header_wrapper">
                                            	<h1><?php echo $email_heading; ?></h1>
                                            </td>
                                        </tr>
                                    </table>
                                    
                                </td>
                            </tr>

//////

Eso estaba abajo de esta linea:

              	<table border="0" cellpadding="0" cellspacing="0" width="600" id="template_container">
