### ISSUE TITLE
contestar test en UNA carga

### ISSUE THREAD

**Issue by myfreckle** [Ganacontrol/myfreckle#79]
LO QUE TE PUSE EN SLACK: 

te acuerdas que me habias dicho que el test se podia hacer en solo una descarga o en varias (ahorotia esta en varias para que contara como "views" y ayudara a la pagina? )

[12:59]  
te tengo que pedir que sea al revez pls! lo hicieron dos amigas y me dijeron que estaba de flojera que se cargue todas las preguntas,, a una le dio flojera seguir contestando el test!

**Comment by Ganacontrol** [comment]
listo
