### ISSUE TITLE
Menu principal

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#8]
Yessica, podrias decirme que secciones deseas en el menu principal?

**Comment by myfreckle** [comment]
Hola! Si, seria ... Home, Jewelry , About, My Freckle

**Comment by myfreckle** [comment]
De la linea rosa que está hasta arriba los iconos hacen que se vea blanco atras y no se ve cool.. hay forma de que yo te pase los iconos con transparencia abajo y que se vea el rosa atras? te mando screen por waffle.

**Comment by myfreckle** [comment]
una duda enorme tmb, en el menu se ven unas rayas. hay forma de quitarlas o ni de chiste? (las que dividen las palabras del menu)

**Comment by Ganacontrol** [comment]
Done. Cerrare este issue. Si tienes comentarios porfa vuelvelo a abrir despues de comentar.
