### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/myfreckle#9]
El favicon es el simbolo que aparece al lado del nombre de tu pagina en un navegador, facebook tiene la f, google tiene la g. Etc.

Quiero suponer que el nuestro sera un freckle.

Necesito el freckle en 16px por 16px en PNG fondo transparente. 
Actualmente puse yo uno de muestra, pero tiene un fondo blanco y esta centrado, nose como lo quieras pero si me mandas el archivo de 16px por 16px lo subo perfecto para que no se pixelee.

**Comment by myfreckle** [comment]
Va! Dejame te lo mando

**Comment by myfreckle** [comment]
Done!
